-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2020-06-27 22:51:31.521

-- tables
-- Table: COMIDA
CREATE TABLE COMIDA (
    IDCOM int  NOT NULL,
    NOMCOM int  NOT NULL,
    CSTCOM int  NOT NULL,
    ESTCOM char(1)  NOT NULL,
    IDINV int  NOT NULL,
    CONSTRAINT COMIDA_pk PRIMARY KEY  (IDCOM)
);

-- Table: INVENTARIO
CREATE TABLE INVENTARIO (
    IDINV int  NOT NULL,
    FECINV date  NOT NULL,
    TIPINV char(5)  NOT NULL,
    CSTPRO numeric(3,2)  NOT NULL,
    PREVENINV numeric(3,2)  NOT NULL,
    COMIDA_IDCOM int  NOT NULL,
    CONSTRAINT INVENTARIO_pk PRIMARY KEY  (IDINV)
);

-- Table: PERSONA
CREATE TABLE PERSONA (
    IDPER int  NOT NULL,
    NOMPER char(20)  NOT NULL,
    APEPER char(20)  NOT NULL,
    TIPPER char(10)  NOT NULL,
    DNIPER numeric(8,0)  NOT NULL,
    TELPER numeric(8)  NOT NULL,
    SEXPER char(1)  NOT NULL,
    ESTPER char(1)  NOT NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY  (IDPER)
);

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    IDPRO int  NOT NULL,
    NOMPRO char(10)  NOT NULL,
    CSTPRO int  NOT NULL,
    ESTPRO char(1)  NOT NULL,
    IDINV int  NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY  (IDPRO)
);

-- Table: VENTA
CREATE TABLE VENTA (
    IDVEN int  NOT NULL,
    IDPER int  NOT NULL,
    TIPVEN char(10)  NOT NULL,
    NOMPER int  NOT NULL,
    FECVEN date  NOT NULL,
    RUC char(11)  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY  (IDVEN)
);

-- Table: VENTA_DETALLE
CREATE TABLE VENTA_DETALLE (
    IDVENDET int  NOT NULL,
    IDVEN int  NOT NULL,
    IDPRO int  NOT NULL,
    IDINV int  NOT NULL,
    IDCOM int  NOT NULL,
    NOMPER char(20)  NOT NULL,
    CANVENDET numeric(20,20)  NOT NULL,
    HORVENDET time  NOT NULL,
    COMVENDET char(30)  NOT NULL,
    TIPPER char(10)  NOT NULL,
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY  (IDVENDET)
);

-- foreign keys
-- Reference: INVENTARIO_COMIDA (table: INVENTARIO)
ALTER TABLE INVENTARIO ADD CONSTRAINT INVENTARIO_COMIDA
    FOREIGN KEY (COMIDA_IDCOM)
    REFERENCES COMIDA (IDCOM);

-- Reference: PRODUCTO_INVENTARIO (table: PRODUCTO)
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_INVENTARIO
    FOREIGN KEY (IDINV)
    REFERENCES INVENTARIO (IDINV);

-- Reference: VENTA_DETALLE_COMIDA (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_COMIDA
    FOREIGN KEY (IDCOM)
    REFERENCES COMIDA (IDCOM);

-- Reference: VENTA_DETALLE_INVENTARIO (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_INVENTARIO
    FOREIGN KEY (IDINV)
    REFERENCES INVENTARIO (IDINV);

-- Reference: VENTA_DETALLE_PRODUCTO (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_PRODUCTO
    FOREIGN KEY (IDPRO)
    REFERENCES PRODUCTO (IDPRO);

-- Reference: VENTA_DETALLE_VENTA (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVEN)
    REFERENCES VENTA (IDVEN);

-- Reference: VENTA_PERSONA (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_PERSONA
    FOREIGN KEY (IDPER)
    REFERENCES PERSONA (IDPER);

-- End of file.

