SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[spcrearPersona] 
@NOMPER varchar(20),
@APEPATPER varchar(20),
@APEMATPER varchar(20),
@TIPPER char(1),
@SEXPER char(1),
@DNIPER char(8),
@TELPER char (9),
@ESTPER char(1),
@DIRPER varchar(100)

AS
INSERT INTO PERSONA
(NOMPER,APEPATPER,APEMATPER,TIPPER,SEXPER,DNIPER,TELPER,ESTPER,DIRPER)
VALUES
(@NOMPER,@APEPATPER,@APEMATPER,@TIPPER,@SEXPER,@DNIPER,@TELPER,@ESTPER,@DIRPER)
GO
