SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[pcactuaPersona]
	@IDPER int ,
	@NOMPER varchar (20),
	@APEPATPER varchar(20),
	@APEMATPER varchar(20),
	@TIPPER char(1),
	@DNIPER	char(8),
	@TELPER char(9),
	@SEXPER char(1),
	@ESTPER char(1),
	@DIRPER char(100)
	

AS
UPDATE PERSONA SET NOMPER=@NOMPER, APEPATPER=@APEPATPER, APEMATPER=@APEMATPER, TIPPER=@TIPPER, DNIPER=@DNIPER, TELPER=@TELPER, SEXPER=@SEXPER, ESTPER=@ESTPER, DIRPER=@DIRPER WHERE IDPER=@IDPER
GO
