CREATE TABLE [dbo].[VENTA]
(
[IDVEN] [int] NOT NULL IDENTITY(1, 1),
[IDPER] [int] NOT NULL,
[TIPVEN] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMPER] [int] NOT NULL,
[FECVEN] [date] NOT NULL,
[RUC] [char] (11) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_pk] PRIMARY KEY CLUSTERED  ([IDVEN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
