CREATE TABLE [dbo].[COMIDA]
(
[IDCOM] [int] NOT NULL IDENTITY(1, 1),
[NOMCOM] [int] NOT NULL,
[CSTCOM] [int] NOT NULL,
[ESTCOM] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMIDA] ADD CONSTRAINT [COMIDA_pk] PRIMARY KEY CLUSTERED  ([IDCOM]) ON [PRIMARY]
GO
