CREATE TABLE [dbo].[ASIGNACION_COMIDA]
(
[IDASICOM] [int] NOT NULL IDENTITY(1, 1),
[IDCOM] [int] NOT NULL,
[FECHASICOM] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASIGNACION_COMIDA] ADD CONSTRAINT [ASIGNACION_COMIDA_pk] PRIMARY KEY CLUSTERED  ([IDASICOM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASIGNACION_COMIDA] ADD CONSTRAINT [Table_8_COMIDA] FOREIGN KEY ([IDCOM]) REFERENCES [dbo].[COMIDA] ([IDCOM])
GO
