CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CSTPRO] [int] NOT NULL,
[ESTPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CANPRO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED  ([IDPRO]) ON [PRIMARY]
GO
