CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENDET] [int] NOT NULL IDENTITY(1, 1),
[IDVEN] [int] NOT NULL,
[IDPRO] [int] NOT NULL,
[NOMPER] [char] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CANVENDET] [numeric] (20, 20) NOT NULL,
[HORVENDET] [time] NOT NULL,
[COMVENDET] [char] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TIPPER] [char] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDASICOM] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_pk] PRIMARY KEY CLUSTERED  ([IDVENDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_ASIGNACION_COMIDA] FOREIGN KEY ([IDASICOM]) REFERENCES [dbo].[ASIGNACION_COMIDA] ([IDASICOM])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_PRODUCTO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTO] ([IDPRO])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_VENTA] FOREIGN KEY ([IDVEN]) REFERENCES [dbo].[VENTA] ([IDVEN])
GO
