CREATE TABLE [dbo].[SUCURSAL]
(
[IDSUC] [int] NOT NULL IDENTITY(1, 1),
[NOMSUC] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DISSUC] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDPER] [int] NOT NULL,
[ESTSUC] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUCURSAL] ADD CONSTRAINT [SUCURSAL_pk] PRIMARY KEY CLUSTERED  ([IDSUC]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SUCURSAL] ADD CONSTRAINT [SUCURSAL_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
