CREATE TABLE [dbo].[LOGIN]
(
[IDLOG] [int] NOT NULL IDENTITY(1, 1),
[USELOG] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PASLOG] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTLOG] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDPER] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOGIN] ADD CONSTRAINT [LOGIN_pk] PRIMARY KEY CLUSTERED  ([IDLOG]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LOGIN] ADD CONSTRAINT [LOGIN_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
