CREATE TABLE [dbo].[PRODUCTO]
(
[IDPRO] [int] NOT NULL,
[NOMPRO] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TIPPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[COSPRO] [decimal] (4, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED  ([IDPRO]) ON [PRIMARY]
GO
