CREATE TABLE [dbo].[VENTA]
(
[IDVEN] [int] NOT NULL IDENTITY(1, 1),
[TIPVEN] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PAGVEN] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDPER] [int] NOT NULL,
[IDSUC] [int] NOT NULL,
[FECVEN] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_pk] PRIMARY KEY CLUSTERED  ([IDVEN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[PERSONA] ([IDPER])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_SUCURSAL] FOREIGN KEY ([IDSUC]) REFERENCES [dbo].[SUCURSAL] ([IDSUC])
GO
